server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: demo
    password: demopass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    datatype:
      datetime:
        WRITE_DATES_AS_TIMESTAMPS: false
